### ISSUE TITLE
Error on paint the result using front camera

### ISSUE THREAD

**Issue by ziselos** [abbyysdk/RTR-SDK.Android#9]
I run the sample code but instead of back camera, i use front one. I want to start another activity after successful recognition. Front camera opens but on recognition i got this error:

`java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
                                                                            at activity.recognition.RecognitionActivity$SurfaceViewWithOverlay.setLines(RecognitionActivity.java:1067)
                                                                            at activity.recognition.RecognitionActivity$1.onFrameProcessed(RecognitionActivity.java:160)
                                                                            at com.abbyy.mobile.rtr.DataCaptureService$Worker$1.run(DataCaptureService.java:583)
                                                                            at android.os.Handler.handleCallback(Handler.java:815)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                            at android.os.Looper.loop(Looper.java:207)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5683)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)`

I think it tries to paint the result on screen but the fact that i open the front camera is a problem. Using back camera, the code runs correctly without errors.

**Comment by aleksey-ka** [comment]
**ArrayIndexOutOfBoundsException** (with length=0; index=0) - trying to access the first element of an empty array. Most probably you are trying to pass an empty array to **setLines** and the code inside **setLines** expects it to be either null or not empty.

The problem is not inside the RTR SDK library, but in the application code using it.

**Comment by ziselos** [comment]
Thanks for your response. I use the front camera and that's why I needed to increase the font size of my text. Now i can recognize the data successfuly.
